function out = model
%
% ML_Test_Solve.m
%
% Model exported on Mar 13 2024, 13:09 by COMSOL 5.6.0.401.

Theta1 = num2str((params(1)));
Phi1   = num2str((params(2)));
X_Tip1 = num2str((params(3)));
Y_Tip1 = num2str((params(4)));
Z_Tip1 = num2str((params(5)));
Theta2 = num2str((params(6)));
Phi2   = num2str((params(7)));
X_Tip2 = num2str((params(8)));
Y_Tip2 = num2str((params(9)));
Z_Tip2 = num2str((params(10)));






import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('D:\COMSOL Models\ML_Test');

model.label('ML_Test_Solve.mph');

model.comments(['Core cref 07292014\n\n']);

model.param.set('rho_blood', '1e3[kg/m^3]', 'Density, blood');
model.param.set('Cp_blood', '3639[J/(kg*K)]', 'Specific heat, blood');
model.param.set('omega_blood', '.0015  [1/s]', 'Blood perfusion rate');
model.param.set('T_blood', '12[degC]', 'Blood temperature');
model.param.set('eps_liver', '46.8', 'Relative permittivity, liver');
model.param.set('sigma_liver', '.861 [S/m]', 'Electric conductivity, liver');
model.param.set('k_liver', '.521   [W/(m*K)]', 'Thermal conductivity, liver');
model.param.set('eps_diel', '2.03', 'Relative permittivity, dielectric');
model.param.set('eps_cat', '1', 'Relative permittivity, catheter');
model.param.set('f', '915 [MHz]', 'Microwave frequency');
model.param.set('P_in', '60  [W]', 'Input microwave power');
model.param.set('rho_liver', '1050   [kg/m^3]', 'Desnity Liver');
model.param.set('cp_liver', '3400  [J/(kg*K)]', 'Heat Capacity at a Constant Pressure');
model.param.set('T_init', '290.15[K]', 'temperature, initial');
model.param.set('T_necro', '353[K]', 'temperature, necrosis');
model.param.set('time_step', '15 [s]', 'time, step');
model.param.set('time_end', '900[s]', 'time, end');
model.param.set('w_tissue', '48', 'diameter, tissue');
model.param.set('h_tissue', '26.8844', 'height minus probe depth, tissue');
model.param.set('d_probe', '55.9356', 'depth, probe');
model.param.set('K1', '0.272580976267724');
model.param.set('S1', '0.187626600378728');
model.param.set('E1', '60.9122091900363');
model.param.set('C1', '1417.02563272972');
model.param.set('ATest', '1.88e41 [1/s]');
model.param.set('EATest', '2.8e5 [J/mol]');
model.param.set('htcoef', '980');
model.param.set('T_probe', '290.15');
model.param.set('K2', '1');
model.param.set('S2', '0');
model.param.set('E2', '2');
model.param.set('C2', '2030');

model.component.create('comp1', false);

model.component('comp1').geom.create('geom1', 3);

model.component('comp1').defineLocalCoord(false);

model.component('comp1').curvedInterior(false);

model.result.table.create('evl3', 'Table');
model.result.table.create('evl2', 'Table');

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').lengthUnit('mm');
model.component('comp1').geom('geom1').scaleUnitValue(true);
model.component('comp1').geom('geom1').geomRep('comsol');
model.component('comp1').geom('geom1').repairTolType('relative');
model.component('comp1').geom('geom1').create('imp1', 'Import');
model.component('comp1').geom('geom1').feature('imp1').set('type', 'native');
model.component('comp1').geom('geom1').feature('imp1').set('filename', 'D:\1.0 Vanderbilt\Dr. Miga Lab\3. Liver Project - Ablation - 2021\COMSOL\COMSOL_PROBE.mphbin');
model.component('comp1').geom('geom1').create('rot1', 'Rotate');
model.component('comp1').geom('geom1').feature('rot1').label('Rotate Set-Up 1');
model.component('comp1').geom('geom1').feature('rot1').set('axis', [90 0]);
model.component('comp1').geom('geom1').feature('rot1').setIndex('rot', '90', 0);
model.component('comp1').geom('geom1').feature('rot1').selection('input').set({'imp1'});
model.component('comp1').geom('geom1').create('rot2', 'Rotate');
model.component('comp1').geom('geom1').feature('rot2').label('Angle (Theta) Rotation 1');
model.component('comp1').geom('geom1').feature('rot2').set('axis', [90 0]);

%Theta 1 Rotation
model.component('comp1').geom('geom1').feature('rot2').setIndex('rot', Theta1, 0);
model.component('comp1').geom('geom1').feature('rot2').selection('input').set({'rot1'});
model.component('comp1').geom('geom1').create('rot3', 'Rotate');
model.component('comp1').geom('geom1').feature('rot3').setIndex('rot', '90', 0);
model.component('comp1').geom('geom1').feature('rot3').selection('input').set({'rot2'});
model.component('comp1').geom('geom1').create('rot4', 'Rotate');
model.component('comp1').geom('geom1').feature('rot4').label('Phi Rotation 1');


%Phi 1 Rotations
model.component('comp1').geom('geom1').feature('rot4').setIndex('rot', Phi1, 0);
model.component('comp1').geom('geom1').feature('rot4').selection('input').set({'rot3'});


% X1   Y1   Z1 Rotation
model.component('comp1').geom('geom1').create('mov1', 'Move');
model.component('comp1').geom('geom1').feature('mov1').setIndex('displx', X_Tip1, 0);
model.component('comp1').geom('geom1').feature('mov1').setIndex('disply', Y_Tip1, 0);
model.component('comp1').geom('geom1').feature('mov1').selection('input').set({'rot4'});


model.component('comp1').geom('geom1').create('imp3', 'Import');
model.component('comp1').geom('geom1').feature('imp3').set('type', 'native');
model.component('comp1').geom('geom1').feature('imp3').set('filename', 'D:\1.0 Vanderbilt\Dr. Miga Lab\3. Liver Project - Ablation - 2021\COMSOL\COMSOL_PROBE.mphbin');
model.component('comp1').geom('geom1').create('rot5', 'Rotate');
model.component('comp1').geom('geom1').feature('rot5').label('Rotate Set-Up 2');
model.component('comp1').geom('geom1').feature('rot5').set('axis', [90 0]);
model.component('comp1').geom('geom1').feature('rot5').setIndex('rot', '90', 0);
model.component('comp1').geom('geom1').feature('rot5').selection('input').set({'imp3'});
model.component('comp1').geom('geom1').create('rot6', 'Rotate');
model.component('comp1').geom('geom1').feature('rot6').label('Angle (Theta) Rotation 2');
model.component('comp1').geom('geom1').feature('rot6').set('axis', [90 0]);


%Theta 2 Rotation
model.component('comp1').geom('geom1').feature('rot6').setIndex('rot', Theta2, 0);
model.component('comp1').geom('geom1').feature('rot6').selection('input').set({'rot5'});
model.component('comp1').geom('geom1').create('rot7', 'Rotate');
model.component('comp1').geom('geom1').feature('rot7').label('Z-Axis Set Up');
model.component('comp1').geom('geom1').feature('rot7').setIndex('rot', '90', 0);
model.component('comp1').geom('geom1').feature('rot7').selection('input').set({'rot6'});
model.component('comp1').geom('geom1').create('rot8', 'Rotate');
model.component('comp1').geom('geom1').feature('rot8').label('Phi Rotation 2');


%Phi 2 Rotations
model.component('comp1').geom('geom1').feature('rot8').setIndex('rot', Phi2, 0);
model.component('comp1').geom('geom1').feature('rot8').selection('input').set({'rot7'});


% X1   Y1   Z1 Rotation
model.component('comp1').geom('geom1').create('mov2', 'Move');
model.component('comp1').geom('geom1').feature('mov2').setIndex('displx', X_Tip2, 0);
model.component('comp1').geom('geom1').feature('mov2').setIndex('disply', Y_Tip2, 0);
model.component('comp1').geom('geom1').feature('mov2').selection('input').set({'rot8'});
model.component('comp1').geom('geom1').create('blk1', 'Block');
model.component('comp1').geom('geom1').feature('blk1').set('pos', [0 0 0]);
model.component('comp1').geom('geom1').feature('blk1').set('base', 'center');
model.component('comp1').geom('geom1').feature('blk1').set('size', [95 95 95]);
model.component('comp1').geom('geom1').feature('fin').set('repairtoltype', 'relative');
model.component('comp1').geom('geom1').run;
model.component('comp1').geom('geom1').run('fin');

model.component('comp1').selection.create('sel1', 'Explicit');
model.component('comp1').selection.create('sel2', 'Explicit');
model.component('comp1').selection.create('sel3', 'Explicit');
model.component('comp1').selection.create('sel4', 'Explicit');
model.component('comp1').selection('sel1').label('Explicit 1 Liver');
model.component('comp1').selection('sel2').label('Explicit 2 Catheter');
model.component('comp1').selection('sel3').label('Explicit 3 Dielectric');
model.component('comp1').selection('sel4').label('Explicit 4 Air');

model.view.create('view2', 2);
model.view.create('view3', 2);
model.view.create('view4', 2);
model.view.create('view6', 2);
model.view.create('view7', 3);
model.view.create('view9', 2);

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material.create('mat3', 'Common');
model.component('comp1').material.create('mat4', 'Common');
model.component('comp1').material.create('mat2', 'Common');
model.component('comp1').material('mat1').selection.set([1]);
model.component('comp1').material('mat1').propertyGroup('def').func.create('pw1', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('pw6', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('pw8', 'Piecewise');
model.component('comp1').material('mat3').selection.set([2 4 8 10 11 12 17 18]);
model.component('comp1').material('mat4').selection.set([3 6 13 15]);
model.component('comp1').material('mat2').selection.set([9 19]);
model.component('comp1').material('mat2').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('comp1').material('mat2').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('comp1').material('mat2').propertyGroup('def').func.create('rho', 'Analytic');
model.component('comp1').material('mat2').propertyGroup('def').func.create('k', 'Piecewise');
model.component('comp1').material('mat2').propertyGroup('def').func.create('cs', 'Analytic');
model.component('comp1').material('mat2').propertyGroup.create('RefractiveIndex', 'Refractive index');

model.component('comp1').physics.create('emw', 'ElectromagneticWaves', 'geom1');
model.component('comp1').physics('emw').selection.set([1 2 3 6 8 9 11 13 15 17 19]);
model.component('comp1').physics('emw').create('sctr1', 'Scattering', 2);
model.component('comp1').physics('emw').feature('sctr1').selection.set([1 2 3 4 5 32 35 38 44 115 124 132 144 212]);
model.component('comp1').physics('emw').create('port1', 'Port', 2);
model.component('comp1').physics('emw').feature('port1').selection.set([118 119 130 136]);
model.component('comp1').physics('emw').create('port2', 'Port', 2);
model.component('comp1').physics('emw').feature('port2').selection.set([12 14 19 24]);
model.component('comp1').physics.create('ht', 'BioHeat', 'geom1');
model.component('comp1').physics('ht').selection.set([1 4 8 10 12 17 18]);
model.component('comp1').physics('ht').feature('bt1').create('opq1', 'Opacity', 3);
model.component('comp1').physics('ht').feature('bt1').create('tdam1', 'ThermalDamage', 3);
model.component('comp1').physics('ht').create('temp1', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp1').selection.set([1 2 3 4 5 32 35 38 44 115 124 132 144 212]);
model.component('comp1').physics('ht').create('hf1', 'HeatFluxBoundary', 2);
model.component('comp1').physics('ht').feature('hf1').selection.set([36 37 42 52 60 61 71 75 76 85 88 95 99 100 104 106 125 126 147 152 165 166 171 172 182 186 187 189 196 201 204 208]);

model.component('comp1').multiphysics.create('emh1', 'ElectromagneticHeating', 3);
model.component('comp1').multiphysics('emh1').selection('BoundarySelection').set([]);

model.component('comp1').mesh('mesh1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').create('size2', 'Size');
model.component('comp1').mesh('mesh1').create('size3', 'Size');
model.component('comp1').mesh('mesh1').create('size4', 'Size');
model.component('comp1').mesh('mesh1').create('ftet1', 'FreeTet');
model.component('comp1').mesh('mesh1').feature('size1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('size1').selection.set([2 8 9 11 17 19]);
model.component('comp1').mesh('mesh1').feature('size2').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('size2').selection.set([3 6 13 15]);
model.component('comp1').mesh('mesh1').feature('size3').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('size3').selection.set([1]);
model.component('comp1').mesh('mesh1').feature('size4').selection.geom('geom1', 2);
model.component('comp1').mesh('mesh1').feature('size4').selection.set([12 14 19 24 118 119 130 136]);
model.component('comp1').mesh('mesh1').feature('ftet1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('ftet1').selection.set([1 2 3 4 6 8 9 10 11 12 13 15 17 18 19]);

model.result.table('evl3').label('Evaluation 3D');
model.result.table('evl3').comments('Interactive 3D values');
model.result.table('evl2').label('Evaluation 2D');
model.result.table('evl2').comments('Interactive 2D values');

model.thermodynamics.label('Thermodynamics Package');

model.component('comp1').view('view1').set('renderwireframe', true);
model.component('comp1').view('view1').set('transparency', true);
model.view('view2').axis.set('xmin', -2.0624139308929443);
model.view('view2').axis.set('xmax', 5.367108345031738);
model.view('view2').axis.set('ymin', -3.437506675720215);
model.view('view2').axis.set('ymax', 2.9398574829101562);
model.view('view3').axis.set('xmin', -7.193136215209961);
model.view('view3').axis.set('xmax', 9.881057739257812);
model.view('view3').axis.set('ymin', -5.602834224700928);
model.view('view3').axis.set('ymax', 9.053338050842285);
model.view('view4').axis.set('xmin', -1.1610738039016724);
model.view('view4').axis.set('xmax', 1.1610738039016724);
model.view('view6').axis.set('xmin', 39.980979919433594);
model.view('view6').axis.set('xmax', 190.94461059570312);
model.view('view6').axis.set('ymin', 116.36117553710938);
model.view('view6').axis.set('ymax', 232.2479705810547);
model.view('view9').axis.set('xmin', 55.38673400878906);
model.view('view9').axis.set('xmax', 184.1410369873047);
model.view('view9').axis.set('ymin', 126.33307647705078);
model.view('view9').axis.set('ymax', 229.77670288085938);

model.component('comp1').material('mat1').label('Liver');
model.component('comp1').material('mat1').propertyGroup('def').func('pw1').label('Thermal Conductivity 2.1');
model.component('comp1').material('mat1').propertyGroup('def').func('pw1').set('funcname', 'therm_cp_2');
model.component('comp1').material('mat1').propertyGroup('def').func('pw1').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('pw1').set('pieces', {'37' '100' 'k_liver*(1+.00092*( T -37))'; '100' '300' 'k_liver*(1-.00092*(100-37) )'});
model.component('comp1').material('mat1').propertyGroup('def').func('pw1').set('argunit', 'degC');
model.component('comp1').material('mat1').propertyGroup('def').func('pw1').set('fununit', 'W/(m*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('pw6').label('Permittivity 2.1');
model.component('comp1').material('mat1').propertyGroup('def').func('pw6').set('funcname', 'Epsilonr_iso2');
model.component('comp1').material('mat1').propertyGroup('def').func('pw6').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('pw6').set('pieces', {'0' '95' '.0172*(T)+ (eps_liver - .39)'; '95' '100' '-3.40*(T)+ (eps_liver + 320.97)'; '100' '300' '(eps_liver - 19.03)'});
model.component('comp1').material('mat1').propertyGroup('def').func('pw6').set('argunit', 'degC');
model.component('comp1').material('mat1').propertyGroup('def').func('pw6').set('fununit', '1');
model.component('comp1').material('mat1').propertyGroup('def').func('pw8').label('Electrical Conductivity3.1');
model.component('comp1').material('mat1').propertyGroup('def').func('pw8').set('funcname', 'Ec3');
model.component('comp1').material('mat1').propertyGroup('def').func('pw8').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('pw8').set('pieces', {'0' '95' '.00897*T + (sigma_liver -.3372)'; '95' '100' '-.112*T + (sigma_liver  + 11.16)'; '100' '300' 'sigma_liver - .04'});
model.component('comp1').material('mat1').propertyGroup('def').func('pw8').set('argunit', 'degC');
model.component('comp1').material('mat1').propertyGroup('def').func('pw8').set('fununit', 'S/m');
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'cp_liver');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho_liver');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'therm_cp_2(T)' '0' '0' '0' 'therm_cp_2(T)' '0' '0' '0' 'therm_cp_2(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('frequencyfactor', '7.39E+39');
model.component('comp1').material('mat1').propertyGroup('def').set('activationenergy', '257700');
model.component('comp1').material('mat1').propertyGroup('def').set('relpermittivity', {'Epsilonr_iso2(T)' '0' '0' '0' 'Epsilonr_iso2(T)' '0' '0' '0' 'Epsilonr_iso2(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('def').set('electricconductivity', {'Ec3(T)' '0' '0' '0' 'Ec3(T)' '0' '0' '0' 'Ec3(T)'});
model.component('comp1').material('mat3').label('Catheter');
model.component('comp1').material('mat3').propertyGroup('def').set('relpermittivity', {'eps_cat' '0' '0' '0' 'eps_cat' '0' '0' '0' 'eps_cat'});
model.component('comp1').material('mat3').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat3').propertyGroup('def').set('electricconductivity', {'0' '0' '0' '0' '0' '0' '0' '0' '0'});
model.component('comp1').material('mat3').propertyGroup('def').set('thermalconductivity', {'K2' '0' '0' '0' 'K2' '0' '0' '0' 'K2'});
model.component('comp1').material('mat3').propertyGroup('def').set('density', '1079[kg/m^3]');
model.component('comp1').material('mat3').propertyGroup('def').set('heatcapacity', 'C2');
model.component('comp1').material('mat3').propertyGroup('def').set('frequencyfactor', '7.39E+39');
model.component('comp1').material('mat3').propertyGroup('def').set('activationenergy', '1e30');
model.component('comp1').material('mat4').label('Dielectric');
model.component('comp1').material('mat4').propertyGroup('def').set('relpermittivity', {'eps_diel' '0' '0' '0' 'eps_diel' '0' '0' '0' 'eps_diel'});
model.component('comp1').material('mat4').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat4').propertyGroup('def').set('electricconductivity', {'0' '0' '0' '0' '0' '0' '0' '0' '0'});
model.component('comp1').material('mat2').label('Air');
model.component('comp1').material('mat2').set('family', 'air');
model.component('comp1').material('mat2').propertyGroup('def').func('eta').set('arg', 'T');
model.component('comp1').material('mat2').propertyGroup('def').func('eta').set('pieces', {'200.0' '1600.0' '-8.38278E-7+8.35717342E-8*T^1-7.69429583E-11*T^2+4.6437266E-14*T^3-1.06585607E-17*T^4'});
model.component('comp1').material('mat2').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('comp1').material('mat2').propertyGroup('def').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('comp1').material('mat2').propertyGroup('def').func('rho').set('expr', 'pA*0.02897/8.314/T');
model.component('comp1').material('mat2').propertyGroup('def').func('rho').set('args', {'pA' 'T'});
model.component('comp1').material('mat2').propertyGroup('def').func('rho').set('dermethod', 'manual');
model.component('comp1').material('mat2').propertyGroup('def').func('rho').set('argders', {'pA' 'd(pA*0.02897/8.314/T,pA)'; 'T' 'd(pA*0.02897/8.314/T,T)'});
model.component('comp1').material('mat2').propertyGroup('def').func('rho').set('plotargs', {'pA' '0' '1'; 'T' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('def').func('k').set('arg', 'T');
model.component('comp1').material('mat2').propertyGroup('def').func('k').set('pieces', {'200.0' '1600.0' '-0.00227583562+1.15480022E-4*T^1-7.90252856E-8*T^2+4.11702505E-11*T^3-7.43864331E-15*T^4'});
model.component('comp1').material('mat2').propertyGroup('def').func('cs').set('expr', 'sqrt(1.4*287*T)');
model.component('comp1').material('mat2').propertyGroup('def').func('cs').set('args', {'T'});
model.component('comp1').material('mat2').propertyGroup('def').func('cs').set('dermethod', 'manual');
model.component('comp1').material('mat2').propertyGroup('def').func('cs').set('argders', {'T' 'd(sqrt(1.4*287*T),T)'});
model.component('comp1').material('mat2').propertyGroup('def').func('cs').set('plotargs', {'T' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('def').set('dynamicviscosity', 'eta(T[1/K])[Pa*s]');
model.component('comp1').material('mat2').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.component('comp1').material('mat2').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.component('comp1').material('mat2').propertyGroup('def').set('heatcapacity', 'Cp(T[1/K])[J/(kg*K)]');
model.component('comp1').material('mat2').propertyGroup('def').set('density', 'rho(pA[1/Pa],T[1/K])[kg/m^3]');
model.component('comp1').material('mat2').propertyGroup('def').set('thermalconductivity', {'k(T[1/K])[W/(m*K)]' '0' '0' '0' 'k(T[1/K])[W/(m*K)]' '0' '0' '0' 'k(T[1/K])[W/(m*K)]'});
model.component('comp1').material('mat2').propertyGroup('def').set('soundspeed', 'cs(T[1/K])[m/s]');
model.component('comp1').material('mat2').propertyGroup('def').addInput('temperature');
model.component('comp1').material('mat2').propertyGroup('def').addInput('pressure');
model.component('comp1').material('mat2').propertyGroup('RefractiveIndex').set('n', '');
model.component('comp1').material('mat2').propertyGroup('RefractiveIndex').set('ki', '');
model.component('comp1').material('mat2').propertyGroup('RefractiveIndex').set('n', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat2').propertyGroup('RefractiveIndex').set('ki', {'0' '0' '0' '0' '0' '0' '0' '0' '0'});

model.component('comp1').physics('emw').prop('EquationForm').set('form', 'Frequency');
model.component('comp1').physics('emw').prop('EquationForm').set('freq_src', 'userdef');
model.component('comp1').physics('emw').prop('EquationForm').set('freq', 'f');
model.component('comp1').physics('emw').prop('BackgroundField').set('w0', 0);
model.component('comp1').physics('emw').prop('BackgroundField').set('Ebg', [0; 0; 0]);
model.component('comp1').physics('emw').prop('AnalysisMethodology').set('MethodologyOptions', 'Robust');
model.component('comp1').physics('emw').feature('wee1').set('minput_temperature_src', 'userdef');
model.component('comp1').physics('emw').feature('wee1').set('minput_temperature', 'T_init');
model.component('comp1').physics('emw').feature('wee1').set('minput_frequency', 'root.freq');
model.component('comp1').physics('emw').feature('wee1').set('editModelInputs', true);
model.component('comp1').physics('emw').feature('sctr1').set('WaveType', 'SphericalWave');
model.component('comp1').physics('emw').feature('port1').set('Pdep', 1);
model.component('comp1').physics('emw').feature('port1').set('Pin', 'P_in');
model.component('comp1').physics('emw').feature('port1').set('PortType', 'Coaxial');
model.component('comp1').physics('emw').feature('port2').set('PortExcitation', 'on');
model.component('comp1').physics('emw').feature('port2').set('Pin', 'P_in');
model.component('comp1').physics('emw').feature('port2').set('PortType', 'Coaxial');
model.component('comp1').physics('ht').prop('PhysicalModelProperty').set('BackCompStateT', 0);
model.component('comp1').physics('ht').prop('PhysicalModelProperty').set('hasThermalDamageFeature', false);
model.component('comp1').physics('ht').prop('PhysicalModelProperty').set('Tref', 'T_init');
model.component('comp1').physics('ht').prop('ConsistentStabilization').set('glim', '(0.01[K])/ht.helem');
model.component('comp1').physics('ht').prop('RadiationSettings').set('opaque', 'ht.dfltopaque');
model.component('comp1').physics('ht').feature('bt1').set('minput_strainreferencetemperature_src', 'userdef');
model.component('comp1').physics('ht').feature('bt1').set('minput_strainreferencetemperature', 'T_init');
model.component('comp1').physics('ht').feature('bt1').feature('bh1').set('Tb', 'T_init');
model.component('comp1').physics('ht').feature('bt1').feature('bh1').set('Cp_b', 'Cp_blood');
model.component('comp1').physics('ht').feature('bt1').feature('bh1').set('omegab', 'omega_blood');
model.component('comp1').physics('ht').feature('bt1').feature('bh1').set('rhobl', 'rho_blood');
model.component('comp1').physics('ht').feature('bt1').feature('opq1').label('Opaque 1');
model.component('comp1').physics('ht').feature('bt1').feature('tdam1').set('TransformationModel', 'ArrheniusKinetics');
model.component('comp1').physics('ht').feature('bt1').feature('tdam1').set('t_dh', 50);
model.component('comp1').physics('ht').feature('bt1').feature('tdam1').set('A', '7.39e39');
model.component('comp1').physics('ht').feature('bt1').feature('tdam1').set('deltaE', '2.577e5');
model.component('comp1').physics('ht').feature('init1').set('Tinit', 'T_init');
model.component('comp1').physics('ht').feature('temp1').set('T0', 'T_init');
model.component('comp1').physics('ht').feature('hf1').set('HeatFluxType', 'ConvectiveHeatFlux');
model.component('comp1').physics('ht').feature('hf1').set('h', 'htcoef');
model.component('comp1').physics('ht').feature('hf1').set('Text', 'T_probe');

model.component('comp1').multiphysics('emh1').label('Electromagnetic Heat Source 1');

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 2);
model.component('comp1').mesh('mesh1').feature('size1').set('hauto', 2);
model.component('comp1').mesh('mesh1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size1').set('hmax', '65.530');
model.component('comp1').mesh('mesh1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('size1').set('hmin', '0.16600');
model.component('comp1').mesh('mesh1').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hauto', 2);
model.component('comp1').mesh('mesh1').feature('size2').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size2').set('hmax', '45.990');
model.component('comp1').mesh('mesh1').feature('size2').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hmin', '0.16600');
model.component('comp1').mesh('mesh1').feature('size2').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('size3').set('hauto', 2);
model.component('comp1').mesh('mesh1').feature('size3').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size3').set('hmax', 6);
model.component('comp1').mesh('mesh1').feature('size3').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('size3').set('hmin', '0.16600');
model.component('comp1').mesh('mesh1').feature('size3').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('size3').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('size3').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('size3').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('size4').set('hauto', 2);
model.component('comp1').mesh('mesh1').feature('size4').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size4').set('hmax', '0.33230');
model.component('comp1').mesh('mesh1').feature('size4').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('size4').set('hmin', '0.0099700');
model.component('comp1').mesh('mesh1').feature('size4').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('size4').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('size4').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('size4').set('hgradactive', true);
model.component('comp1').mesh('mesh1').run;

model.study.create('std1');
model.study('std1').create('freq', 'Frequency');
model.study('std1').create('time', 'Transient');
model.study('std1').feature('freq').set('activate', {'emw' 'on' 'ht' 'off'});
model.study('std1').feature('time').set('activate', {'emw' 'off' 'ht' 'on'});

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').create('st2', 'StudyStep');
model.sol('sol1').create('v2', 'Variables');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('sv1', 'SORVector');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('sv1', 'SORVector');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol('sol1').feature('t1').create('se1', 'Segregated');
model.sol('sol1').feature('t1').create('i1', 'Iterative');
model.sol('sol1').feature('t1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol1').feature('t1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol1').feature('t1').feature('se1').feature.remove('ssDef');
model.sol('sol1').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature.remove('fcDef');

model.result.dataset.create('dset2', 'Solution');
model.result.dataset.create('cpl3', 'CutPlane');
model.result.dataset.create('cln1', 'CutLine2D');
model.result.dataset.create('cpt1', 'CutPoint2D');
model.result.dataset.create('cpl4', 'CutPlane');
model.result.dataset('cpl3').set('data', 'dset2');
model.result.dataset('cpl4').set('data', 'dset2');
model.result.dataset.remove('dset1');
model.result.numerical.create('gev1', 'EvalGlobal');
model.result.numerical('gev1').set('probetag', 'none');
model.result.create('pg1', 'PlotGroup3D');
model.result.create('pg3', 'PlotGroup3D');
model.result.create('pg2', 'PlotGroup3D');
model.result.create('pg4', 'PlotGroup2D');
model.result.create('pg5', 'PlotGroup2D');
model.result.create('pg6', 'PlotGroup2D');
model.result.create('pg7', 'PlotGroup3D');
model.result.create('pg8', 'PlotGroup3D');
model.result.create('pg9', 'PlotGroup3D');
model.result.create('pg10', 'PlotGroup3D');
model.result.create('pg11', 'PlotGroup3D');
model.result.create('pg13', 'PlotGroup1D');
model.result.create('pg14', 'PlotGroup2D');
model.result('pg1').create('mslc1', 'Multislice');
model.result('pg3').create('iso1', 'Isosurface');
model.result('pg3').create('arwv1', 'ArrowVolume');
model.result('pg3').create('con1', 'Contour');
model.result('pg3').feature('iso1').set('expr', 'T');
model.result('pg3').feature('con1').set('expr', 'T');
model.result('pg2').create('surf1', 'Surface');
model.result('pg2').feature('surf1').set('expr', 'T');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('expr', 'log10(comp1.emw.normE)');
model.result('pg5').create('surf1', 'Surface');
model.result('pg5').create('con1', 'Contour');
model.result('pg5').feature('surf1').set('expr', 'T');
model.result('pg5').feature('con1').set('expr', 'T');
model.result('pg6').create('surf1', 'Surface');
model.result('pg6').create('con1', 'Contour');
model.result('pg6').feature('surf1').set('expr', 'ht.theta_d');
model.result('pg6').feature('con1').set('expr', 'ht.theta_d');
model.result('pg7').create('mslc1', 'Multislice');
model.result('pg8').create('surf1', 'Surface');
model.result('pg8').feature('surf1').set('expr', 'T');
model.result('pg9').create('iso1', 'Isosurface');
model.result('pg9').feature('iso1').set('expr', 'T');
model.result('pg10').create('mslc1', 'Multislice');
model.result('pg10').create('slc1', 'Slice');
model.result('pg10').feature('mslc1').set('data', 'dset2');
model.result('pg10').feature('mslc1').set('expr', 'T');
model.result('pg10').feature('slc1').set('data', 'dset2');
model.result('pg10').feature('slc1').set('expr', 'T');
model.result('pg11').create('iso1', 'Isosurface');
model.result('pg11').feature('iso1').set('expr', 'ht.theta_d');
model.result('pg11').feature('iso1').create('filt1', 'Filter');
model.result('pg11').feature('iso1').feature('filt1').set('expr', 'ht.theta_d > 0.8');
model.result('pg13').create('ptgr1', 'PointGraph');
model.result('pg13').feature('ptgr1').set('expr', 'T');
model.result('pg14').create('surf1', 'Surface');
model.result('pg14').create('con1', 'Contour');
model.result('pg14').feature('surf1').set('expr', 'T');
model.result('pg14').feature('con1').set('expr', 'T');
model.result.export.create('data1', 'Data');
model.result.export.create('data2', 'Data');

model.study('std1').feature('freq').set('punit', 'Hz');
model.study('std1').feature('freq').set('plist', 'f');
model.study('std1').feature('freq').set('plot', false);
model.study('std1').feature('freq').set('probesel', 'none');
model.study('std1').feature('time').set('tunit', 'min');
model.study('std1').feature('time').set('tlist', 'range(0,0.25,15)');

model.sol('sol1').attach('std1');
model.sol('sol1').label('Solver 1');
model.sol('sol1').feature('st1').label('Compile Equations: Frequency Domain');
model.sol('sol1').feature('v1').label('Dependent Variables 1.1');
model.sol('sol1').feature('v1').set('clistctrl', {'p1' 't1_timestep'});
model.sol('sol1').feature('v1').set('cname', {'freq' 'timestep'});
model.sol('sol1').feature('v1').set('clist', {'f' '0.015[min]'});
model.sol('sol1').feature('s1').label('Stationary Solver 1.1');
model.sol('sol1').feature('s1').set('probesel', 'none');
model.sol('sol1').feature('s1').feature('dDef').label('Direct 1');
model.sol('sol1').feature('s1').feature('dDef').set('thresh', 0.1);
model.sol('sol1').feature('s1').feature('dDef').set('ooc', false);
model.sol('sol1').feature('s1').feature('dDef').set('rhob', 400);
model.sol('sol1').feature('s1').feature('aDef').label('Advanced 1');
model.sol('sol1').feature('s1').feature('aDef').set('complexfun', true);
model.sol('sol1').feature('s1').feature('p1').label('Parametric 1.1');
model.sol('sol1').feature('s1').feature('p1').set('pname', {'freq'});
model.sol('sol1').feature('s1').feature('p1').set('plistarr', {'f'});
model.sol('sol1').feature('s1').feature('p1').set('punit', {'Hz'});
model.sol('sol1').feature('s1').feature('p1').set('pcontinuationmode', 'no');
model.sol('sol1').feature('s1').feature('p1').set('preusesol', 'auto');
model.sol('sol1').feature('s1').feature('p1').set('probesel', 'none');
model.sol('sol1').feature('s1').feature('fc1').label('Fully Coupled 1.1');
model.sol('sol1').feature('s1').feature('i1').label('Iterative 1.1');
model.sol('sol1').feature('s1').feature('i1').set('linsolver', 'bicgstab');
model.sol('sol1').feature('s1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sv1').label('SOR Vector 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sv1').set('sorvecdof', {'comp1_E'});
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sv1').label('SOR Vector 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sv1').set('sorvecdof', {'comp1_E'});
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').set('thresh', 0.1);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').set('ooc', false);
model.sol('sol1').feature('st2').label('Compile Equations: Time Dependent');
model.sol('sol1').feature('st2').set('studystep', 'time');
model.sol('sol1').feature('v2').label('Dependent Variables 2.1');
model.sol('sol1').feature('v2').set('initmethod', 'sol');
model.sol('sol1').feature('v2').set('initsol', 'sol1');
model.sol('sol1').feature('v2').set('solnum', 'auto');
model.sol('sol1').feature('v2').set('notsolmethod', 'sol');
model.sol('sol1').feature('v2').set('notsol', 'sol1');
model.sol('sol1').feature('v2').set('notsolnum', 'auto');
model.sol('sol1').feature('v2').set('clist', {'range(0,0.25,15)' '0.015[min]'});
model.sol('sol1').feature('t1').label('Time-Dependent Solver 1.1');
model.sol('sol1').feature('t1').set('control', 'time');
model.sol('sol1').feature('t1').set('tunit', 'min');
model.sol('sol1').feature('t1').set('tlist', 'range(0,0.25,15)');
model.sol('sol1').feature('t1').set('atolglobalvaluemethod', 'manual');
model.sol('sol1').feature('t1').set('atolvaluemethod', {'comp1_T' 'manual' 'comp1_ht_alpha' 'manual' 'comp1_E' 'manual'});
model.sol('sol1').feature('t1').set('maxorder', 2);
model.sol('sol1').feature('t1').set('estrat', 'exclude');
model.sol('sol1').feature('t1').feature('dDef').label('Direct 1');
model.sol('sol1').feature('t1').feature('dDef').set('thresh', 0.1);
model.sol('sol1').feature('t1').feature('dDef').set('ooc', false);
model.sol('sol1').feature('t1').feature('dDef').set('rhob', 400);
model.sol('sol1').feature('t1').feature('aDef').label('Advanced 1');
model.sol('sol1').feature('t1').feature('se1').label('Segregated 1.1');
model.sol('sol1').feature('t1').feature('se1').feature('ss1').label('Segregated Step 1.1');
model.sol('sol1').feature('t1').feature('se1').feature('ss1').set('segvar', {'comp1_T'});
model.sol('sol1').feature('t1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol1').feature('t1').feature('se1').feature('ss2').label('Segregated Step 2.1');
model.sol('sol1').feature('t1').feature('se1').feature('ss2').set('segvar', {'comp1_ht_alpha'});
model.sol('sol1').feature('t1').feature('i1').label('Iterative 1.1');
model.sol('sol1').feature('t1').feature('i1').set('rhob', 20);
model.sol('sol1').feature('t1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('seconditer', 2);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').set('thresh', 0.1);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').set('ooc', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('ooc', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pardreorder', 'ndmt');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotstrategy', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pardmtsolve', false);
model.sol('sol1').runAll;

model.result.dataset('cpl3').set('quickplane', 'xy');
model.result.dataset('cpl3').set('quickz', 140);
model.result.dataset('cln1').set('genpoints', [103.641 129.579; 101.334 163.207]);
model.result.dataset('cpt1').set('pointx', '167, 167, 167, 167,167, 167, 167, 167');
model.result.dataset('cpt1').set('pointy', '145, 150, 155, 160, 135, 130, 125, 120');
model.result.dataset('cpl4').set('quickplane', 'xy');
model.result.dataset('cpl4').set('quickz', 141);
model.result.numerical('gev1').label('S-parameter, S11dB (emw)');
model.result.numerical('gev1').set('expr', {'emw.S11dB'});
model.result.numerical('gev1').set('unit', {''});
model.result.numerical('gev1').set('descr', {'S-parameter, dB, 11 component'});
model.result('pg1').label('Electric Field (emw)');
model.result('pg1').set('looplevel', [1]);
model.result('pg1').set('frametype', 'mesh');
model.result('pg1').set('showlegendsmaxmin', true);
model.result('pg1').feature('mslc1').set('smooth', 'internal');
model.result('pg1').feature('mslc1').set('resolution', 'normal');
model.result('pg3').label('Isothermal Contours (ht)');
model.result('pg3').set('looplevel', [1]);
model.result('pg3').set('showhiddenobjects', true);
model.result('pg3').set('showlegendsmaxmin', true);
model.result('pg3').feature('iso1').set('solrepresentation', 'solnum');
model.result('pg3').feature('iso1').set('unit', 'degC');
model.result('pg3').feature('iso1').set('levelmethod', 'levels');
model.result('pg3').feature('iso1').set('levels', 60);
model.result('pg3').feature('iso1').set('colortable', 'ThermalEquidistant');
model.result('pg3').feature('iso1').set('smooth', 'internal');
model.result('pg3').feature('iso1').set('resolution', 'normal');
model.result('pg3').feature('arwv1').set('expr', {'ht.tfluxx' 'ht.tfluxy' 'ht.tfluxz'});
model.result('pg3').feature('arwv1').set('descr', 'Total heat flux');
model.result('pg3').feature('arwv1').set('arrowlength', 'logarithmic');
model.result('pg3').feature('arwv1').set('scale', 3.338159792807751);
model.result('pg3').feature('arwv1').set('color', 'gray');
model.result('pg3').feature('arwv1').set('scaleactive', false);
model.result('pg3').feature('con1').set('unit', 'degC');
model.result('pg3').feature('con1').set('levelrounding', false);
model.result('pg3').feature('con1').set('legendtype', 'lines');
model.result('pg3').feature('con1').set('smooth', 'internal');
model.result('pg3').feature('con1').set('resolution', 'normal');
model.result('pg2').label('Temperature (ht)');
model.result('pg2').set('looplevel', [1]);
model.result('pg2').set('showlegendsmaxmin', true);
model.result('pg2').feature('surf1').set('colortable', 'ThermalLight');
model.result('pg2').feature('surf1').set('smooth', 'internal');
model.result('pg2').feature('surf1').set('resolution', 'normal');
model.result('pg4').label('2D Electric Field Norm');
model.result('pg4').set('data', 'cpl4');
model.result('pg4').set('looplevel', [1]);
model.result('pg4').set('showlegendsmaxmin', true);
model.result('pg4').feature('surf1').set('smooth', 'internal');
model.result('pg4').feature('surf1').set('resolution', 'normal');
model.result('pg5').label('2D Temperature');
model.result('pg5').set('looplevel', [1]);
model.result('pg5').set('titletype', 'custom');
model.result('pg5').set('filenameintitle', true);
model.result('pg5').set('typeintitle', false);
model.result('pg5').set('titleparamindicator', false);
model.result('pg5').set('xlabelactive', true);
model.result('pg5').set('showlegendsmaxmin', true);
model.result('pg5').feature('surf1').set('unit', 'degC');
model.result('pg5').feature('surf1').set('titletype', 'custom');
model.result('pg5').feature('surf1').set('typeintitle', false);
model.result('pg5').feature('surf1').set('descriptionintitle', false);
model.result('pg5').feature('surf1').set('unitintitle', false);
model.result('pg5').feature('surf1').set('rangecoloractive', true);
model.result('pg5').feature('surf1').set('rangecolormin', 28.9201443600047);
model.result('pg5').feature('surf1').set('rangecolormax', 216.08199966245652);
model.result('pg5').feature('surf1').set('rangedataactive', true);
model.result('pg5').feature('surf1').set('rangedatamin', 35);
model.result('pg5').feature('surf1').set('rangedatamax', 216.08199966245652);
model.result('pg5').feature('surf1').set('smooth', 'internal');
model.result('pg5').feature('surf1').set('resolution', 'normal');
model.result('pg5').feature('con1').set('unit', 'degC');
model.result('pg5').feature('con1').set('levelrounding', false);
model.result('pg5').feature('con1').set('colortable', 'GrayScale');
model.result('pg5').feature('con1').set('colorlegend', false);
model.result('pg5').feature('con1').set('legendtype', 'lines');
model.result('pg5').feature('con1').set('smooth', 'internal');
model.result('pg5').feature('con1').set('resolution', 'normal');
model.result('pg6').label('2D Necrosis');
model.result('pg6').set('showlegendsmaxmin', true);
model.result('pg6').feature('surf1').set('descr', 'Fraction of necrotic tissue');
model.result('pg6').feature('surf1').set('rangecoloractive', true);
model.result('pg6').feature('surf1').set('rangecolormin', 0.25);
model.result('pg6').feature('surf1').set('rangecolormax', 1);
model.result('pg6').feature('surf1').set('colortable', 'RainbowLight');
model.result('pg6').feature('surf1').set('smooth', 'everywhere');
model.result('pg6').feature('surf1').set('threshold', 'manual');
model.result('pg6').feature('surf1').set('thresholdvalue', 0.7);
model.result('pg6').feature('surf1').set('recover', 'pprint');
model.result('pg6').feature('surf1').set('resolution', 'normal');
model.result('pg6').feature('con1').active(false);
model.result('pg6').feature('con1').set('descr', 'Fraction of necrosed tissue');
model.result('pg6').feature('con1').set('number', 10);
model.result('pg6').feature('con1').set('levelrounding', false);
model.result('pg6').feature('con1').set('colortable', 'GrayScale');
model.result('pg6').feature('con1').set('legendtype', 'filled');
model.result('pg6').feature('con1').set('smooth', 'everywhere');
model.result('pg6').feature('con1').set('threshold', 'manual');
model.result('pg6').feature('con1').set('thresholdvalue', '.95');
model.result('pg6').feature('con1').set('resolution', 'normal');
model.result('pg7').label('Electric Field (emw) 1');
model.result('pg7').set('looplevel', [1]);
model.result('pg7').set('frametype', 'spatial');
model.result('pg7').feature('mslc1').set('smooth', 'internal');
model.result('pg7').feature('mslc1').set('resolution', 'normal');
model.result('pg8').label('Temperature (ht) 1');
model.result('pg8').set('looplevel', [1]);
model.result('pg8').feature('surf1').set('colortable', 'ThermalLight');
model.result('pg8').feature('surf1').set('smooth', 'internal');
model.result('pg8').feature('surf1').set('resolution', 'normal');
model.result('pg9').label('Isothermal Contours (ht) 1');
model.result('pg9').set('looplevel', [1]);
model.result('pg9').feature('iso1').set('unit', 'degC');
model.result('pg9').feature('iso1').set('number', 20);
model.result('pg9').feature('iso1').set('levelrounding', false);
model.result('pg9').feature('iso1').set('interactive', true);
model.result('pg9').feature('iso1').set('shift', 12);
model.result('pg9').feature('iso1').set('contourlabels', true);
model.result('pg9').feature('iso1').set('colortable', 'ThermalLight');
model.result('pg9').feature('iso1').set('smooth', 'internal');
model.result('pg9').feature('iso1').set('resolution', 'normal');
model.result('pg10').label('3D Plot Group _Temperature_Slices');
model.result('pg10').set('looplevel', [1]);
model.result('pg10').feature('mslc1').set('looplevel', [1]);
model.result('pg10').feature('mslc1').set('multiplanexmethod', 'coord');
model.result('pg10').feature('mslc1').set('xcoord', 140);
model.result('pg10').feature('mslc1').set('multiplaneymethod', 'coord');
model.result('pg10').feature('mslc1').set('ycoord', 220);
model.result('pg10').feature('mslc1').set('multiplanezmethod', 'coord');
model.result('pg10').feature('mslc1').set('zcoord', 150);
model.result('pg10').feature('mslc1').set('colortable', 'Thermal');
model.result('pg10').feature('mslc1').set('smooth', 'internal');
model.result('pg10').feature('mslc1').set('resolution', 'normal');
model.result('pg10').feature('slc1').active(false);
model.result('pg10').feature('slc1').set('looplevel', [1]);
model.result('pg10').feature('slc1').set('quickxmethod', 'coord');
model.result('pg10').feature('slc1').set('quickx', 120);
model.result('pg10').feature('slc1').set('smooth', 'internal');
model.result('pg10').feature('slc1').set('resolution', 'normal');
model.result('pg11').label('Isothermal_Necrosis');
model.result('pg11').feature('iso1').set('descr', 'Fraction of necrotic tissue');
model.result('pg11').feature('iso1').set('number', 10);
model.result('pg11').feature('iso1').set('levelrounding', false);
model.result('pg11').feature('iso1').set('smooth', 'internal');
model.result('pg11').feature('iso1').set('resolution', 'normal');
model.result('pg11').feature('iso1').feature('filt1').set('nodespec', 'all');
model.result('pg13').set('data', 'cpt1');
model.result('pg13').set('titletype', 'custom');
model.result('pg13').set('filenameintitle', true);
model.result('pg13').set('xlabel', 'Time (min)');
model.result('pg13').set('ylabel', 'Temperature (degC)');
model.result('pg13').set('window', 'window1');
model.result('pg13').set('windowtitle', 'Plot 1');
model.result('pg13').set('xlabelactive', false);
model.result('pg13').set('ylabelactive', false);
model.result('pg13').feature('ptgr1').set('unit', 'degC');
model.result('pg13').feature('ptgr1').set('linewidth', 3);
model.result('pg13').feature('ptgr1').set('legend', true);
model.result('pg13').feature('ptgr1').set('legendmethod', 'manual');
model.result('pg13').feature('ptgr1').set('legends', {'(124, 140) - 5 mm down' '(124, 135)  - 10 mm down' '(124, 130) - 15 mm down' '(124, 125) - 20 mm down' '(124, 150)  - 5 mm up' '(124, 155) - 10 mm up' '(124, 160) - 15 mm up' '(124, 165) - 20 mm up'});
model.result('pg14').label('2D Temperature 1');
model.result('pg14').set('data', 'cpl4');
model.result('pg14').set('looplevel', [1]);
model.result('pg14').set('titletype', 'custom');
model.result('pg14').set('filenameintitle', true);
model.result('pg14').set('typeintitle', false);
model.result('pg14').set('titleparamindicator', false);
model.result('pg14').set('xlabelactive', true);
model.result('pg14').set('showlegendsmaxmin', true);
model.result('pg14').feature('surf1').set('unit', 'degC');
model.result('pg14').feature('surf1').set('titletype', 'custom');
model.result('pg14').feature('surf1').set('typeintitle', false);
model.result('pg14').feature('surf1').set('descriptionintitle', false);
model.result('pg14').feature('surf1').set('unitintitle', false);
model.result('pg14').feature('surf1').set('colortable', 'RainbowLight');
model.result('pg14').feature('surf1').set('smooth', 'internal');
model.result('pg14').feature('surf1').set('resolution', 'normal');
model.result('pg14').feature('con1').set('unit', 'degC');
model.result('pg14').feature('con1').set('number', 10);
model.result('pg14').feature('con1').set('levelrounding', false);
model.result('pg14').feature('con1').set('colortable', 'GrayScale');
model.result('pg14').feature('con1').set('colorlegend', false);
model.result('pg14').feature('con1').set('legendtype', 'lines');
model.result('pg14').feature('con1').set('smooth', 'internal');
model.result('pg14').feature('con1').set('resolution', 'normal');
model.result.export('data1').set('expr', {'T' 'ht.theta_d' '' ''});
model.result.export('data1').set('unit', {'degC' '1' '' ''});
model.result.export('data1').set('descr', {'Temperature' 'Fraction of necrosed tissue' '' ''});
model.result.export('data1').set('filename', 'D:\Import To Matlab\Box Phantom\MultiprobeRefined\BoxGeomPhantomMultiprobe_TrueBeef5Degrees_UN_Refined.csv');
model.result.export('data1').set('smooth', 'internal');
model.result.export('data1').set('separator', ',');
model.result.export('data2').set('data', 'cpl4');
model.result.export('data2').set('expr', {'emw.Qh'});
model.result.export('data2').set('unit', {'W/m^3'});
model.result.export('data2').set('filename', 'C:\Users\servinf\Documents\1.0 Vanderbilt\Dr. Miga Lab\COMSOL_DATA\915_MHZ_Temps\004__Power_Dissipation_surface_915_MHZ.csv');
model.result.export('data2').set('smooth', 'internal');
model.result.export('data2').set('separator', ',');
model.result.export('data2').set('descr', {'Temperature'});

out = model;
