function [VandyMap] = SelectVandyMapSDA( mapNum)

switch mapNum 
    case 1
        VandyMap  = [ rgb("MidnightBlue"); rgb("DarkBlue"); rgb("RoyalBlue");...
                    rgb("DarkCyan");  rgb("SeaGreen");...
                    rgb("Peru"); rgb("Orange"); rgb("OrangeRed"); ...
                    rgb("FireBrick");  rgb("Maroon")];   
    case 2 

        VandyMap = [ rgb("MidnightBlue"); rgb("DarkBlue"); rgb("RoyalBlue");...
                    rgb("DarkCyan");  rgb("SeaGreen");...
                    rgb("Peru"); rgb("Orange"); rgb("OrangeRed"); ...
                    rgb("FireBrick");  rgb("Maroon")]; 
    case 3 
        VandyMap = [ rgb("MidnightBlue"); rgb("DarkBlue"); rgb("RoyalBlue");...
                    rgb("DarkCyan");  rgb("SeaGreen");...
                    rgb("Peru"); rgb("Peru");  rgb("Orange"); rgb("Orange"); rgb("OrangeRed");  rgb("OrangeRed"); ...
                    rgb("FireBrick"); rgb("FireBrick"); rgb("Maroon"); rgb("Maroon")]; 
    case 4       
        VandyMap = [ rgb("MidnightBlue"); rgb("DarkBlue"); rgb("RoyalBlue");...
                    rgb("DarkCyan");  rgb("SeaGreen");...
                    rgb("Peru"); rgb("Peru"); rgb("Peru"); rgb("Orange"); rgb("Orange");...
                    rgb("Orange"); rgb("OrangeRed");  rgb("OrangeRed"); rgb("OrangeRed"); ...
                    rgb("FireBrick"); rgb("FireBrick"); rgb("Maroon"); rgb("Maroon")];       
    case 5
        VandyMap  = [  repmat(rgb("RoyalBlue"), 5,1) ;...
                    repmat( rgb("BurlyWood"), 5,1) ;repmat( rgb("Peru"), 5,1) ;...
                    repmat( rgb("Orange"), 5,1) ;repmat( rgb("DarkOrange"), 5,1);...
                    repmat( rgb("OrangeRed"), 4, 1) ; repmat( rgb("FireBrick"), 5,1) ;...
                    repmat( rgb("Maroon"), 5,1) ];   

end 