
clc
clear 
close all

% Structuring the multiple-choice questions with MATLAB

% Questions
questions = {
    'Which city has the following universities: University of Toronto and Sunnybrook Research Institute?', ...
    'Which city is home to ETH Zurich and the University of Zurich?', ...
    'Which city hosts Imperial College London and King’s College London?', ...
    'Which city features National University of Singapore and Nanyang Technological University?', ...
    'Which city include Université PSL and Sorbonne Université?', ...
    'Which city houses the University of Tokyo and Tokyo Institute of Technology?', ...
    'Which city is home to University of Sydney and University of New South Wales?', ...
    'Which city has Ludwig Maximilian University and Technical University of Munich?', ...
    'Which city is known for Karolinska Institutet and Royal Institute of Technology (KTH)?', ...
    'Which city has Tsinghua University and Peking University?', ...
    'Which city includes University of Amsterdam and Delft University of Technology?', ...
    'Which city is home to Seoul National University and KAIST?', ...
    'Which city features University of Copenhagen and Technical University of Denmark?', ...
    'Which city hosts Indian Institute of Science and Manipal Academy of Higher Education?', ...
    'Which city includes Hong Kong University of Science and Technology and The Chinese University of Hong Kong?', ...
    'Which city houses Medical University of Vienna and Vienna University of Technology?', ...
    'Which city is known for Politecnico di Milano and University of Milan?', ...
    'Which city has University of British Columbia and McMaster University?', ...
    'Which city hosts Federal University of Rio de Janeiro and Pontifical Catholic University of Rio de Janeiro?', ...
    'Which city is home to KU Leuven and University Hospitals Leuven?'
};

% Answers for each question


% Answers for each question
answers = {
    {'Zurich', 'Toronto', 'Munich', 'Sydney'}, ...
    {'Zurich', 'London', 'Beijing', 'Amsterdam'}, ...
    {'Seoul', 'Singapore', 'London', 'Copenhagen'}, ...
    {'Paris', 'Sydney', 'Singapore', 'Rio de Janeiro'}, ...
    {'Stockholm', 'Vienna', 'Paris', 'Sydney'}, ...
    {'Milan', 'Tokyo', 'Munich', 'Amsterdam'}, ...
    {'Sydney', 'Toronto', 'Seoul', 'Hong Kong'}, ...
    {'Munich', 'Singapore', 'Zurich', 'Vienna'}, ...
    {'Seoul', 'Stockholm', 'Copenhagen', 'Paris'}, ...
    {'Tokyo', 'Beijing', 'Milan', 'London'}, ...
    {'Rio de Janeiro', 'Toronto', 'Amsterdam', 'Stockholm'}, ...
    {'Seoul', 'Vienna', 'Milan', 'Toronto'}, ...
    {'Copenhagen', 'Singapore', 'Paris', 'Beijing'}, ...
    {'Bangalore', 'Sydney', 'Munich', 'London'}, ...
    {'Tokyo', 'Hong Kong', 'Zurich', 'Paris'}, ...
    {'Vienna', 'Munich', 'Zurich', 'Toronto'}, ...
    {'Milan', 'Stockholm', 'Beijing', 'Copenhagen'}, ...
    {'Toronto', 'Munich', 'Sydney', 'Milan'}, ...
    {'Rio de Janeiro', 'Tokyo', 'Copenhagen', 'Hong Kong'}, ...
    {'London', 'Zurich', 'Leuven', 'Bangalore'}
};

% Determine the number of columns
numColumns = 4; % assuming each sub-array has four cities

% Initialize an empty cell array to store answers column-wise
stackedAnswers = cell(numColumns, length(answers));

% Stack answers column-wise
for i = 1:length(answers)
    for j = 1:numColumns
        stackedAnswers{j, i} = answers{i}{j};
    end
end

% Display stacked answers
disp(stackedAnswers);

answers = stackedAnswers;


% Correct Answers
correct_answers = [2, 1, 3, 3, 3, 2, 1, 1, 2, 2, 3, 1, 1, 1, 2, 1, 1, 1, 1, 3];

% Time Limits set to 100 seconds
time_limits = 100 * ones(1, 20);

% Create matrix
Q_A_matrix = [questions.', answers.', num2cell(time_limits.'), num2cell(correct_answers.')];

% Assign column names
column_names = {'Question Text', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'Time Limit (sec)', 'Correct Answer(s)'};

% Convert to table
questions_table = cell2table(Q_A_matrix, 'VariableNames', column_names);

% Display table
disp(questions_table);